### ISSUE TITLE
Kotlin multiplatform support

### ISSUE THREAD

**Issue by jakoss** [GetStream/stream-log#16]
After reviewing the code i think it's feasible to make the `stream-log` module JVM independent. Do you plan on doing so? Even the `stream-log-file` could be adjusted using `Okio` (not 100% sure about that though)

**Comment by skydoves** [comment]
What do you think about this? @kanat @JcMinarro

**Comment by kanat** [comment]
> What do you think about this? @kanat @JcMinarro

Sounds reasonable 👍

**Comment by jakoss** [comment]
Great, it would be awesome to use `stream-log` in shared module and then just use proper sink on any of the platforms :)

**Comment by skydoves** [comment]
#22

**Comment by skydoves** [comment]
Hey @jakoss, it's so late, but now Stream Log supports KMP! Thank you for your suggestion.
